import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Play, Send, TerminalSquare } from 'lucide-react';
import { getQuestions, post, Question } from '../placementApi';
import VideoSidePanel from './VideoSidePanel';
import './PlacementPortal.css';

interface Execution {all_passed?:boolean;passed_count?:number;total_count?:number;error?:string;conceptual?:boolean;matched_key_points?:string[];results?:Array<{test_case:number;status:string;input:string;expected:string;actual:string;runtime_ms:number}>}

export default function CodingWorkspace(){
  const {questionId}=useParams(); const navigate=useNavigate(); const [question,setQuestion]=useState<Question>(); const [language,setLanguage]=useState<'python'|'java'>('python'); const [code,setCode]=useState(''); const [output,setOutput]=useState<Execution>(); const [busy,setBusy]=useState(false);
  useEffect(()=>{getQuestions().then(items=>setQuestion(items.find(q=>q.id===questionId||q.title_slug===questionId)))},[questionId]);
  useEffect(()=>{if(question)setCode(question.starter_code?.[language]||'')},[question,language]);
  const execute=async(mode:'run'|'submit')=>{if(!question)return;setBusy(true);setOutput(undefined);try{setOutput(await post<Execution>(`/api/code/${mode}`,{question_id:question.id,language,source_code:code}))}catch(error){setOutput({error:error instanceof Error?error.message:'Runner unavailable'})}finally{setBusy(false)}};
  if(!question)return <div className="portal-page loading-state">Loading workspace…</div>;
  const isConceptual=question.type==='Conceptual';
  return <div className="studio-shell"><div className="studio-topbar"><button className="ghost-button" onClick={()=>navigate('/workflow')}><ArrowLeft size={16}/> Roadmap</button><div><span>{question.source} · {question.category}</span><strong>{question.title}</strong></div><span className={`difficulty ${question.difficulty.toLowerCase()}`}>{question.difficulty}</span></div><div className="studio-grid">
    <section className="problem-pane"><div className="pane-label">Problem brief</div><h1>{question.title}</h1><div className="chip-row">{question.topics.map(t=><span className="chip" key={t}>{t}</span>)}{question.companies?.slice(0,3).map(c=><span className="chip company-chip" key={c}>{c}</span>)}</div><p className="problem-copy">{question.description}</p>{question.test_cases?.[0]&&<div className="example-box"><span>Example input</span><pre>{question.test_cases[0].input}</pre><span>Expected output</span><pre>{question.test_cases[0].expected}</pre></div>}<div className="workspace-tip"><CheckCircle2/><div><strong>{isConceptual?'Structure your explanation':'Submission standard'}</strong><p>{isConceptual?'Cover the trade-offs and named key concepts.':'Run checks the visible sample. Submit validates private edge cases without exposing their inputs.'}</p></div></div></section>
    <section className="editor-pane"><header><div className="language-tabs"><button className={language==='python'?'active':''} onClick={()=>setLanguage('python')}>Python</button><button className={language==='java'?'active':''} onClick={()=>setLanguage('java')}>Java</button></div><span className="pane-label">Your private workspace</span></header><textarea className="code-editor" spellCheck={false} value={code} onChange={event=>setCode(event.target.value)} aria-label="Code editor" maxLength={50000}/><div className="editor-actions"><button className="btn-secondary" onClick={()=>execute('run')} disabled={busy}><Play size={16}/> {isConceptual?'Check draft':'Run sample checks'}</button><button className="btn-primary" onClick={()=>execute('submit')} disabled={busy}><Send size={16}/> {busy?'Evaluating…':isConceptual?'Submit self-check':'Submit hidden tests'}</button></div><div className="console"><div className="console-title"><TerminalSquare size={15}/> Execution console {output&&<span className={output.all_passed?'console-pass':'console-fail'}>{output.all_passed?'All checks passed':'Needs work'}</span>}</div>{!output?<p>Results will appear here.</p>:output.error?<pre>{output.error}</pre>:output.conceptual?<p>Matched key points: {output.matched_key_points?.join(', ')||'none yet'}</p>:<div className="test-results"><p>{output.passed_count}/{output.total_count} checks passed</p>{output.results?.map(item=><div className={item.status==='Passed'?'test pass':'test fail'} key={item.test_case}><strong>#{item.test_case} {item.status}</strong><span>{item.runtime_ms} ms</span></div>)}</div>}</div></section>
    <VideoSidePanel topic={question.related_videos?.topic_video} problem={question.related_videos?.problem_videos?.[0]}/>
  </div></div>;
}
